spring:
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: r1
            uri: lb://CUSTOMER-SERVICE
            predicates:
              - Path=/customers/**
          - id: r2
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
